\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

	\transpose g a {
		% intro
		g2. | g2. | g2. | g2. |

		% estribillo
		g2. | e2.:m | a2. | d2. |
		b2. | e2.:m | a2. | d2. |
		g2. | e2.:m | c4. d4. |

		% glue
		g2. | g2. | g2. | g2. |

		% te alabamos, te bendecimos...
		g2.:m | ees2. | ees2. | bes4. f4. |
		c2.:m | g2.:m | bes4. f4. | c2.:m |
		d2. | d2. |

		% estribillo
		g2. | e2.:m | a2. | d2. |
		b2. | e2.:m | a2. | d2. |
		g2. | e2.:m | c4. d4. |

		% glue
		g2. | g2. | g2. | g2. |

		% sennor, jesucristo, cordero de dios...
		g2.:m | ees2. | g2.:m | bes4. f4. |
		c2.:m | g2.:m | g2.:m | bes4. f4. |
		c2.:m | d2. | d2. |

		% estribillo
		g2. | e2.:m | a2. | d2. |
		b2. | e2.:m | a2. | d2. |
		g2. | e2.:m | c4. d4. |

		% glue
		g2. | g2. | g2. | g2. |

		% tu que estas sentado...
		g2. | c2. | a2. | d2. |
		b2. | e2.:m | f2. | d2. |
		g2. | e2.:m | c2. | a2.:m |
		g2. | e2.:m | c2. | d2. |
		c2. | d2.

		% finale
		g2. | g2. | e4.:m a4. | d2. |
		g2. | g2. | e4.:m a4. | d2. |
		g2. | g2. | g2. | g2. |
		g2.

	} % end transpose
	} % end chords
